![Accel.AI](https://static1.squarespace.com/static/58dc1a1ee4fcb51cbb80a096/t/58f7170329687f53ff2ca1f7/1492588319632/logo-horiz-SM.png?format=300w)

# Linear Algebra with Python and NumPy

In [1]:
# First, we need to import the package NumPy, which is the library enabling all the fun with algebraic structures.
from numpy import *

## Vectors and Matrices

In [2]:
a = array([10,20,30])   # Define a vector of size 3 using type 'array'
print(a)
print(a.shape)          # Size/shape of vector

b = array([5,5,5])   # Define a vector of size 3 using type 'array'

print(a+b)

print(a*b)

[10 20 30]
(3,)
[15 25 35]
[ 50 100 150]


In [3]:
b = matrix('10 20 30')  # Define a vector of size 3 using type 'matrix'
print(b)
print(b.shape)          # Size/shape of vector

[[10 20 30]]
(1, 3)


In [4]:
A = matrix([[1, 4, 5, 12],
            [-5, 8, 9, 0],
            [-6, 7, 11, 19]])

print(A)

A.shape

[[ 1  4  5 12]
 [-5  8  9  0]
 [-6  7 11 19]]


(3, 4)

In [5]:
a = array([1,2,3])
print(a.shape)
print(type(a))

a = array([ [1,2,3],[3,2,1] ])
print(a.shape)
print(type(a))

(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>


In [6]:
c = linspace(10,20,6)   # Define vector as 6 values evenly spaced from 10 to 20
print(c)
print(type(c))

[10. 12. 14. 16. 18. 20.]
<class 'numpy.ndarray'>


Note that matrix and array elements in Python are indexed from 0, in contrast to Matlab where indexing starts from 1.

In [7]:
print(c[:])     # Get all elements
print(c[0])     # The first element
print(c[-1])    # The last element
print(c[:3])    # The first 3 elements
print(c[-3:])   # The last 3 elemnets
print(c[2:4])   # 2:4 selects elements of indexes 2 and 3

[10. 12. 14. 16. 18. 20.]
10.0
20.0
[10. 12. 14.]
[16. 18. 20.]
[14. 16.]


In [8]:
A = matrix([ [7,7,7],
            [8,8,8]  ])

print(A)
print(A.shape)

[[7 7 7]
 [8 8 8]]
(2, 3)


**_Euclidean norm_** of vector is returned by method `numpy.linalg.norm`

In [9]:
norm = linalg.norm(a)      # Euclidean norm of vector a
print('a =', a)
print('norm(a) =', norm)

x = a/linalg.norm(a)       # Make normalized/unit vector from a
print('x =', x)
print('norm(x) =', linalg.norm(x))

a = [[1 2 3]
 [3 2 1]]
norm(a) = 5.291502622129181
x = [[0.18898224 0.37796447 0.56694671]
 [0.56694671 0.37796447 0.18898224]]
norm(x) = 0.9999999999999999


**_Transposition_** of vectors is not so intuitive as in Matlab, especially if a vector is defined as 1D `array` and you cannot distinguish between row and column vector. However, using the keyword `newaxis` it's possible to shape the vector into 2D array (as matrix of size $1 \times n$ or $n \times 1$), where transposition makes sense and can be obtained by attribute `.T`.

In [10]:
x = a[:,newaxis]  # Make column vector from vector a (defined as array)
print(x)
print(x.shape)    # Now size of column vector is 3x1
print(x.T)        # Make row vector by transpostion of column vector

[[[1 2 3]]

 [[3 2 1]]]
(2, 1, 3)
[[[1 3]]

 [[2 2]]

 [[3 1]]]


If a vector was defined as 2D array of type `matrix`, transportation is not a problem.

In [11]:
x = b.T           # Make column vector from vector b (defined as matrix)
print(x)
print(x.shape)    # Now size of column vector is 3x1
print(x.T)        # Make row vector by transpostion of column vector

[[10]
 [20]
 [30]]
(3, 1)
[[10 20 30]]


**_Matrices_** can be defined as 2D arrays of type `array` or `matrix` (there is no problem with transposition with any type).

In [12]:
A = array([[11,12,13], [21,22,23], [31,32,33]])  # Define matrix of size 3x3 as 2D 'array-type'
print(A)
print(A.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


In [13]:
B = matrix('11 12 13; 21 22 23; 31 32 33')  # Define matrix of size 3x3 as 'matrix-type'
print(B)
print(B.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


In [14]:
print(B[0,1])    # Get matrix element at row 0, column 1
print(B[0,:])    # Get 1st row of matrix (A[0] returns also 1st row)
print(B[:,0])    # Get 1st column of matrix

12
[[11 12 13]]
[[11]
 [21]
 [31]]


In [15]:
print(A[:,0])   # Note that column from 'array-type' matrix is returned as 1D array
print(B[:,0])   # Column from 'matrix-type' matrix is returned as true column as expected

[11 21 31]
[[11]
 [21]
 [31]]


NumPy can generate some essential matrices exactly like Matlab.

In [16]:
print('3x3 Matrix full of zeros:')
print(zeros([3,3]))

print('\n3x3 Matrix full of ones:')
print(ones([3,3]))

print('\n3x3 identity matrix:')
print(eye(3))

print('\n3x3 diagonal matrix:')
x = array([1.,2.,3.])
print(diag(x))

print('\n3x3 random matrix:')
print(random.rand(3,3))

3x3 Matrix full of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

3x3 Matrix full of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3x3 diagonal matrix:
[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]

3x3 random matrix:
[[0.71754984 0.57696389 0.39429936]
 [0.00896188 0.28915838 0.13989351]
 [0.64751209 0.62943678 0.31872283]]


For merging matrices or vectors methods `numpy.hstack` and `numpy.vstack` can be used.

In [17]:
print(vstack([ A, ones([1,3]) ]))  # Add row vector to matrix
print(hstack([ A, ones([3,1]) ]))  # Add column vector to matrix
print(hstack([ A, eye(3) ]))       # Merge two matrices horizontally

[[11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]
 [ 1.  1.  1.]]
[[11. 12. 13.  1.]
 [21. 22. 23.  1.]
 [31. 32. 33.  1.]]
[[11. 12. 13.  1.  0.  0.]
 [21. 22. 23.  0.  1.  0.]
 [31. 32. 33.  0.  0.  1.]]


## Operations with Matrices

**_Matrix transposition_** is obtained by attribute `.T`

In [18]:
X = ones([2,5])     # Generate 2x5 matrix full of ones
Y = X.T             # Obtain transpose of matrix X

print('Matrix X of size', X.shape, ':\n', X)
print('\nMatrix Y=X.T of size', Y.shape, ':\n', Y)

Matrix X of size (2, 5) :
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

Matrix Y=X.T of size (5, 2) :
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


**_Matrix multiplication_** must be executed by method for dot product `numpy.dot`. Operator `*` produces only element-wise multiplication in Python.

In [19]:
print('Matrix A:')
print(A)

print('\nMatrix B:')
B = ones([3,3])
print(B)

print('\nElement-wise multiplication A*B:')
print(A*B)

print('\nMatrix multiplication A by B:')
print(dot(A,B))

print('\nMatrix multiplication B by A:')
print(dot(B,A))

Matrix A:
[[11 12 13]
 [21 22 23]
 [31 32 33]]

Matrix B:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Element-wise multiplication A*B:
[[11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]

Matrix multiplication A by B:
[[36. 36. 36.]
 [66. 66. 66.]
 [96. 96. 96.]]

Matrix multiplication B by A:
[[63. 66. 69.]
 [63. 66. 69.]
 [63. 66. 69.]]


There are also methods for essential matrix features like **_Frobenius norm_**, **_rank_** or **_determinant_**.

In [20]:
print('Matrix A of size', A.shape, ':\n', A)

# Frobenius norm of matrix
print('\nFrobenius norm: ||A|| =', linalg.norm(A))

# Rank of matrix
print('rank(A) =', linalg.matrix_rank(A))

# Determinant of matrix
print('det(A) =',  linalg.det(A))

Matrix A of size (3, 3) :
 [[11 12 13]
 [21 22 23]
 [31 32 33]]

Frobenius norm: ||A|| = 70.44146506142529
rank(A) = 2
det(A) = 0.0


In example above, note that the matrix $\mathbf{A}$ is a singular matrix, because its rank is lower than number of its rows, thus also its detemninat is zero.